const i18n = {
    ru: {
        theme_dark: "🌙 Тёмная",
        theme_light: "☀️ Светлая",
        lang_name: "🇷🇺 RU",
        loading: "Загрузка...",
        next_event: "➡ {event} через {h} ч {m} мин",
        no_next_event: "➡ Нет ближайших событий",
        current_active_event: "🔥 СЕЙЧАС ИДЁТ: {event}",
        current_active_phase_event: "🔥 Фаза {phase}: {event}",
        day_label: "День",
        local_time: "🕒 Локальное время",
        server_time: "🖥️ Время сервера (UTC-2)",
        game_day: "📅 День игры",
        timezone: "Часовой пояс",
        phase_radar: "Фаза 1. Радар",
        phase_build: "Фаза 2. Строительство",
        phase_tech: "Фаза 3. Технологии",
        phase_hero: "Фаза 4. Герой",
        phase_prepare: "Фаза 5. Боеготовность",
        phase_raid: "Фаза 6. Рейд",
        days: ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"],
        events: {
            "Строительство Базы": "Строительство Базы",
            "Обучить Солдат": "Обучить Солдат",
            "Исследования технологий": "Исследования технологий",
            "Улучшение бойца": "Улучшение бойца",
            "Улучшение Героя": "Улучшение Героя"
        },
        tabs: {
            phases: "📅 Фазы",
            score: "🏆 Очки фаз",
            upgrades: "🏗️ Улучшения",
            calendar: "🗓️ События",
            timecalc: "⏱️ Сумматор",
            resources: "💰 Ресурсы",
            itemupgrade: "⚡ Золотые вещи",
            guides: "📖 Инструкции",
            codes: "🎁 Коды",
            video: "🎥 Видео",
            support: "🙏 Спасибо"
        },
        ui: {
            total: "Итого",
            points: "очков",
            next_chest: "Следующий сундук",
            all_chests: "Все сундуки получены!",
            add_points: "➕ Добавить очки",
            select_level: "Выберите уровень базы (1–30):",
            level: "Уровень",
            condition: "Условие",
            no_data: "Нет данных",
            calc_time: "🧮 Сумматор времени",
            reset: "Сбросить",
            reset_all: "Сбросить всё",
            add: "Прибавить",
            subtract: "Вычесть",
            qty: "Кол-во",
            duration: "Длит.",
            items: "Предметы (клик для выбора):",
            conv_title: "🔁 Конвертация компонентов",
            calculate: "Рассчитать",
            gear_title: "⚡ Прокачка золотых вещей (0–40)",
            gear_desc: "Введите текущий и целевой уровень. Стоимость в очищенных камнях и нефти.",
            current_lvl: "Текущий уровень",
            target_lvl: "Целевой уровень",
            stars_title: "⭐ Прокачка звёзд (1⭐ и 2⭐)",
            stars_desc: "Для получения звезды нужно выполнить 5 улучшений по фиксированной цене.",
            star1: "1 звезда (5×12 000 камней, 5×145 кристаллов, 5×20 м нефти)",
            star2: "2 звезда (5×16 000 камней, 5×200 кристаллов, 5×30 м нефти)",
            calc_star: "Рассчитать стоимость звезды",
            stones: "Очищенных камней",
            oil: "Нефти",
            crystals: "Проводящих кристаллов",
            reminders: "Напоминание на",
            current_phase: "🔹 Текущая фаза",
            next_phase_rem: "⏰ До следующей фазы",
            no_next_phase: "⏰ До следующей фазы: нет данных",
            item_qty_err: "Количество > 0",
            select_item_err: "Выберите предмет",
            gear_lvl_err: "Целевой уровень должен быть выше текущего",
            no_gear_data: "Нет данных для уровня",
            st_d: "дн",
            st_h: "ч",
            st_m: "мин",
            st_s: "сек",
            pcs: "шт",
            copy_code: "Нажмите, чтобы скопировать",
            copied: "Скопировано!",
            vs_title: "⚙️ Технологии VS (бонусы в %)",
            vs_bonus_note: "Бонусы суммируются. Очки пересчитываются автоматически.",
            items_header: "📦 Предметы (клик для выбора):",
            conv_chain_desc: "Цепочка: 4 Стали ▸ 1 Стальной компонент ▸ 4 ▸ Жаропрочное золото ▸ 4 ▸ Композитный материал ▸ 4 ▸ Проводящий кристалл (1 кристалл = 256 стали).",
            star1_label: "1 звезда (5×12 000 камней, 5×145 кристаллов, 5×20 м нефти)",
            star2_label: "2 звезда (5×16 000 камней, 5×200 кристаллов, 5×30 м нефти)",
            vs_hint: "🎯 очки VS",
            bonus_labels: {
                "vs_radar": "📡 Радар",
                "vs_build": "🏗️ Строительство",
                "vs_research": "🔬 Исследования",
                "vs_train": "⚔️ Тренировка",
                "vs_hire": "🦸 Найм героев",
                "vs_speed": "⚡ Ускорение",
                "vs_kill": "💀 Убийство/потеря",
                "vs_all": "✨ Общий (все действия)"
            },
            resources: {
                steel: "Сталь",
                steelComp: "Стальной компонент",
                heatGold: "Жаропрочное золото",
                composite: "Композитный материал",
                crystal: "Проводящий кристалл"
            },
            res_names: {
                steel: "стали",
                steelComp: "стальных компонентов",
                heatGold: "жаропрочного золота",
                composite: "композитного материала",
                crystal: "проводящих кристаллов"
            },
            main_subtitle: '<span class="paw">🐾</span> ЕГО ПУШИСТЕЙШЕСТВО <span class="paw">🐾</span>',
            select_lvl_req: "Выберите уровень, чтобы увидеть условия",
            th_action: "Действие",
            th_base: "Базовые очки",
            th_qty: "Количество / суммарно",
            th_total: "Итого",
            k_exp: "тыс. опыта",
            total_units: "всего ед.",
            support_html: `
                <h3>🙏 Спасибо, что пользуетесь помощником!</h3>
                <p>Если этот инструмент помогает вам в игре и вы хотите поддержать его развитие, вы можете сделать добровольное пожертвование. Все средства пойдут на поддержку серверов и создание новых гайдов.</p>
                <p><strong>Важно:</strong> Пожертвование является добровольным и не даёт никаких преимуществ в игре или в использовании помощника. Вы можете пользоваться всеми функциями совершенно бесплатно.</p>
                <p>Реквизиты для поддержки (РФ):</p>
                <ul style="text-align: left; display: inline-block;">
                    <li>МТС: 2203 8302 4197 6290 </li>
                    <li><a href="https://boosty.to/peg40/donate" target="_blank">Поддержать проект на Boosty</a></li>
                </ul>
                <p style="margin-top: 12px;">Или напишите в игре (потом добавим ТГ и мыло) <strong>РЕЗЕРВ</strong> для других способов.</p>
                <p class="small-note" style="margin-top: 12px;">Данный сайт не является публичной офертой. Все платежи являются добровольными.</p>
            `,
            calendar_day: "День {n}"
        },
        buildings: {
            "Полигон": "Полигон",
            "Парковка": "Парковка",
            "Линия обороны": "Линия обороны",
            "Тренировочный лагерь солдат": "Тренировочный лагерь солдат",
            "Центр подготовки (по классу)": "Центр подготовки (по классу)",
            "Отдел альфа-исследований": "Отдел альфа-исследований",
            "Центр альянса": "Центр альянса",
            "Госпиталь": "Госпиталь",
            "Ур.": "Ур."
        },
        tips: {
            "Sunday": ["📡 Не выполняйте задания радара — копите до понедельника.", "🚚 Отправьте отряды в ночь на сбор ресурсов.", "⚡ Подготовьте выносливость и банки."],
            "Monday": ["🎯 Сразу выполните накопленные задания радара.", "💪 Используйте части бойцов, боевые чипы, выносливость.", "🔄 Постоянно отправляйте отряды на сбор ресурсов.", "🤝 Совмещайте с Готовностью к миссии."],
            "Tuesday": ["🏗️ Завершите «призрачную стройку».", "📈 Используйте ускорения постройки.", "✉️ Выполните оранжевую миссию и отправьте легендарный транспортник."],
            "Wednesday": ["🔬 Не тратьте ускорения исследований всю неделю — используйте сегодня.", "📡 Закройте радар.", "📦 Откройте сундуки с компонентами.", "🧪 Запросите Министра науки."],
            "Thursday": ["🦸 Используйте опыт героя, карты найма.", "🎴 Тратьте фрагменты героев (мифические→эпические→редкие).", "📖 Примените книги навыков.", "📡 Копите радар на завтра."],
            "Friday": ["⚔️ Совмещайте ускорения постройки, исследований и тренировок.", "🎓 Обучайте солдат в интервалы.", "🛡️ Подготовьте щит на субботу."],
            "Saturday": ["🏆 Используйте оставшиеся ускорения.", "⚔️ Участвуйте в рейдах, убивайте солдат.", "🛡️ Не бойтесь потерь — они дают очки.", "🚫 Отключите оборону в гарнизоне, держите ресурсы в инвентаре."]
        },
        guides: [
            { 
                title: "💎 Как накопить алмазы?", 
                body: "1. Ежедневные задания (до 500 в день).\n2. Радарные задания (особенно оранжевые).\n3. События альянса (награды за сундуки).\n4. Спецоперации и элитные зомби.\n5. Подарки альянса от покупок соклановцев.\n\nСовет: Не тратьте алмазы на ускорения напрямую, лучше покупайте VIP-очки или предметы в магазине со скидкой." 
            },
            { 
                title: "⚔️ Как подготовиться к Рейду (Суббота)?", 
                body: "1. Копите щиты (8ч или 24ч).\n2. Нанимайте больше войск в пятницу.\n3. Спрячьте ресурсы в инвентарь (не открывайте сундуки).\n4. Уберите войска из обороны, если не планируете защищаться.\n\nПомните: В субботу главное — убивать войска противника, а не защищать базу." 
            },
            { 
                title: "🏗️ Приоритеты строительства", 
                body: "1. База (открывает новые уровни).\n2. Тренировочные лагеря (увеличивают уровень войск).\n3. Научный центр (ускоряет развитие).\n4. Полигон (увеличивает размер отряда).\n\nСовет: Стройте только то, что необходимо для улучшения Базы, чтобы быстрее дойти до Т9/Т10 войск." 
            }
        ],
        videos: [
            {
                title: "Переход между серверами",
                description: "Видео-инструкция: как перепрыгнуть с одного сервера на другой.",
                src: "assets/video/ServJ.mp4"
            }
        ],
        phase_names: ["Радар", "Строительство", "Технологии", "Герой", "Боеготовность", "Рейд"],
        calendar_days: ["День 1 (Воскресенье)","День 2 (Понедельник)","День 3 (Вторник)","День 4 (Среда)","День 5 (Четверг)","День 6 (Пятница)","День 7 (Суббота)"],
        phase_tips: {
            "Воскресенье": "📡 Копим радар",
            "Понедельник": "🎯 Радар + сбор",
            "Вторник": "🏗️ Стройка",
            "Среда": "🔬 Технологии",
            "Четверг": "🦸 Герои",
            "Пятница": "⚔️ Боеготовность",
            "Суббота": "🏆 Рейд"
        },
        score_actions: {
            "Потратить 1 Выносливость": "Потратить 1 Выносливость",
            "Выполнить задание Радара": "Выполнить задание Радара",
            "Использовать 660 опыта Героя": "Использовать 660 опыта Героя",
            "Набор с алмазами [1 алмаз]": "Набор с алмазами [1 алмаз]",
            "Собрать 100 ед. еды": "Собрать 100 ед. еды",
            "Собрать 100 ед. металла": "Собрать 100 ед. металла",
            "Собрать 60 ед. нефти": "Собрать 60 ед. нефти",
            "Использовать 1 Боевой чип бойца": "Использовать 1 Боевой чип бойца",
            "Использовать 1 Часть бойца": "Использовать 1 Часть бойца",
            "За каждую минуту ускорения постройки": "За каждую минуту ускорения постройки",
            "За каждую постройку +1 Мощь": "За каждую постройку +1 Мощь",
            "Выполнить 1 оранжевую миссию Спецопераций": "Выполнить 1 оранжевую миссию Спецопераций",
            "Отправить 1 Легендарный Транспортник": "Отправить 1 Легендарный Транспортник",
            "Провести 1 призыв выжившего": "Провести 1 призыв выжившего",
            "Завершить событие Радара": "Завершить событие Радара",
            "Использовать 1 минуту ускорения исследования": "Использовать 1 минуту ускорения исследования",
            "Завершить исследование за +1 Силу": "Завершить исследование за +1 Силу",
            "Потратить 1 Научные данные": "Потратить 1 Научные данные",
            "Открыть сундук с компонентами бойца": "Открыть сундук с компонентами бойца",
            "Нанять героя 1 раз": "Нанять героя 1 раз",
            "Использовать 1 Мифический Осколок Героя": "Использовать 1 Мифический Осколок Героя",
            "Использовать 1 Эпический Осколок Героя": "Использовать 1 Эпический Осколок Героя",
            "Использовать 1 Редкий Осколок Героя": "Использовать 1 Редкий Осколок Героя",
            "Использовать 1 Книгу опыта навыков": "Использовать 1 Книгу опыта навыков",
            "За каждую минуту ускорения исследований": "За каждую минуту ускорения исследований",
            "За каждое исследование +1 Сила": "За каждое исследование +1 Сила",
            "Ускорение тренировок (1 мин.)": "Ускорение тренировок (1 мин.)",
            "Обучить Т1 Солдата": "Обучить Т1 Солдата",
            "Обучить Т2 Солдата": "Обучить Т2 Солдата",
            "Обучить Солдата Т3": "Обучить Солдата Т3",
            "Обучить Солдата Т4": "Обучить Солдата Т4",
            "Обучить Солдата Т5": "Обучить Солдата Т5",
            "Обучить Солдата Т6": "Обучить Солдата Т6",
            "Обучить Солдата Т7": "Обучить Солдата Т7",
            "Обучить Солдата Т8": "Обучить Солдата Т8",
            "Облучить Солдата Т8": "Обучить Солдата Т8",
            "За каждого уничтоженного бойца T7": "За каждого уничтоженного бойца T7",
            "За каждого уничтоженного солдата T8": "За каждого уничтоженного солдата T8",
            "За каждого уничтоженного солдата T9": "За каждого уничтоженного солдата T9",
            "За каждого уничтоженного солдата T10": "За каждого уничтоженного солдата T10",
            "За каждого потерянного солдата T1": "За каждого потерянного солдата T1",
            "За каждого потерянного солдата T2": "За каждого потерянного солдата T2",
            "За каждого потерянного солдата T3": "За каждого потерянного солдата T3",
            "За каждого погибшего солдата T4": "За каждого погибшего солдата T4",
            "За каждого погибшего солдата T5": "За каждого погибшего солдата T5",
            "За каждого погибшего солдата T6": "За каждого погибшего солдата T6",
            "За каждого погибшего солдата T7": "За каждого погибшего солдата T7",
            "За каждого погибшего солдата T8": "За каждого погибшего солдата T8",
            "За каждого погибшего солдата T9": "За каждого погибшего солдата T9",
            "За каждого потерянного бойца T10": "За каждого потерянного бойца T10"
        },
        phases_raw: [
            ["Воскресенье", "", "События радара (Копим на завтра)", "Отправляем в ночь отряды на сбор ресурсов."],
            ["Понедельник", "Фаза 1. Радар", "Завершить событие Радара", "Сразу выполняйте накопленные задания радара."],
            ["", "", "Использовать 1 Часть бойца", "Используйте части бойцов."],
            ["", "", "Использовать 1 Боевой чип бойца", "Используйте боевые чипы."],
            ["", "", "Потратить 1 Выносливость", "Тратьте выносливость на задания радара."],
            ["", "", "Использовать 660 опыта Героя", "Приберечь для фазы героя."],
            ["", "", "Сбор 100 ед. ресурсов", "Как только отряды вернулись — сразу отправляйте их снова на сбор."],
            ["Вторник", "Фаза 2. Строительство", "Использовать 1 минуту ускорения постройки", "Завершите заранее начатые стройки."],
            ["", "", "Завершить постройку за +1 Мощь", "Используйте ускорения постройки."],
            ["", "", "Выполнить 1 оранжевую миссию", "Используйте жетоны для поиска."],
            ["", "", "Отправить 1 Легендарный Транспортник", "Используйте контракты конвоя."],
            ["", "", "", "События радара (Копим на завтра)."],
            ["Среда", "Фаза 3. Технологии", "Завершить событие Радара", "Закройте все доступные события радара."],
            ["", "", "Использовать 1 минуту ускорения исследования", "Используйте ускорения исследований."],
            ["", "", "Завершить исследование за +1 Силу", "Завершайте самые долгие технологии."],
            ["", "", "Потратить 1 Научные данные", "Тратьте научные данные."],
            ["", "", "Открыть сундук с компонентами бойца", "Откройте все накопленные сундуки."],
            ["Четверг", "Фаза 4. Герой", "Использовать 660 опыта Героя", "Используйте опыт героя."],
            ["", "", "Использовать карту найма героя", "Используйте карты найма первыми."],
            ["", "", "Фрагмент героя или универс. (Мифический)", "Тратьте мифические фрагменты."],
            ["", "", "Фрагмент героя или универс. (Эпический)", "Тратьте эпические фрагменты."],
            ["", "", "Фрагмент героя или универс. (Редкий)", "Тратьте редкие фрагменты."],
            ["", "", "Использовать книгу навыков", "Примените книги навыков."],
            ["", "", "", "События радара (Копим на завтра)."],
            ["Пятница", "Фаза 5. Боеготовность", "Завершить событие Радара", "Закройте радар."],
            ["", "", "Использовать 1 минуту ускорения постройки", "Используйте ускорения постройки."],
            ["", "", "Завершить постройку за +1 Мощь", "Завершайте стройки."],
            ["", "", "Использовать 1 минуту ускорения исследования", "Используйте ускорения исследований."],
            ["", "", "Завершить исследование за +1 Силу", "Завершайте исследования."],
            ["", "", "Использовать 1 минуту ускорения тренировок", "Используйте ускорения тренировок."],
            ["", "", "Обучить солдат", "Начинайте обучение солдат (очки сразу)."],
            ["Суббота", "Фаза 6. Рейд", "Использовать 1 минуту ускорения постройки", "Используйте оставшиеся ускорения постройки."],
            ["", "", "Использовать 1 минуту ускорения исследования", "Используйте оставшиеся ускорения исследований."],
            ["", "", "Использовать 1 минуту ускорения тренировок", "Используйте оставшиеся ускорения тренировок."],
            ["", "", "Использовать 1 минуту ускорения лечения", "Используйте ускорения лечения."],
            ["", "", "Убийство солдат противника", "Атакуйте базы, убивайте солдат."],
            ["", "", "Смерть своих солдат", "Не бойтесь потерь — они дают очки."]
        ],
        base_score: {
            "Радар":[["Потратить 1 Выносливость",150],["Выполнить задание Радара",10000],["Использовать 660 опыта Героя",1],["Набор с алмазами [1 алмаз]",30],["Собрать 100 ед. еды",20],["Собрать 100 ед. металла",20],["Собрать 60 ед. нефти",20],["Использовать 1 Боевой чип бойца",3],["Использовать 1 Часть бойца",2500]],
            "Строительство":[["Набор с алмазами [1 алмаз]",30],["За каждую минуту ускорения постройки",60],["За каждую постройку +1 Мощь",10],["Выполнить 1 оранжевую миссию Спецопераций",75000],["Отправить 1 Легендарный Транспортник",100000],["Провести 1 призыв выжившего",1500]],
            "Технологии":[["Завершить событие Радара",10000],["Использовать 1 минуту ускорения исследования",60],["Завершить исследование за +1 Силу",10],["Потратить 1 Научные данные",100],["Открыть сундук с компонентами бойца",500]],
            "Герой":[["Использовать 660 опыта Героя",1],["Набор с алмазами [1 алмаз]",30],["Нанять героя 1 раз",1500],["Использовать 1 Мифический Осколок Героя",10000],["Использовать 1 Эпический Осколок Героя",3500],["Использовать 1 Редкий Осколок Героя",1000],["Использовать 1 Книгу опыта навыков",10]],
            "Боеготовность":[["Выполнить задание Радара",10000],["Набор с алмазами [1 алмаз]",30],["За каждую минуту ускорения постройки",60],["За каждую постройку +1 Мощь",10],["За каждую минуту ускорения исследований",60],["За каждое исследование +1 Сила",10],["Ускорение тренировок (1 мин.)",60],["Обучить Т1 Солдата",20],["Обучить Т2 Солдата",30],["Обучить Солдата Т3",40],["Обучить Солдата Т4",50],["Обучить Солдата Т5",60],["Обучить Солдата Т6",70],["Обучить Солдата Т7",80],["Облучить Солдата Т8",90]],
            "Рейд":[["За каждого уничтоженного бойца T7",18],["За каждого уничтоженного солдата T8",20],["За каждого уничтоженного солдата T9",23],["За каждого уничтоженного солдата T10",25],["За каждого потерянного солдата T1",4],["За каждого потерянного солдата T2",6],["За каждого потерянного солдата T3",8],["За каждого погибшего солдата T4",10],["За каждого погибшего солдата T5",12],["За каждого погибшего солдата T6",14],["За каждого погибшего солдата T7",16],["За каждого погибшего солдата T8",18],["За каждого погибшего солдата T9",20],["За каждого потерянного бойца T10",22],["Отправить 1 Легендарный Транспортник",200000]]
        },
        event_labels: {
            "Улучшение бойца": "Боец",
            "Улучшение Героя": "Герой",
            "Строительство Базы": "Стройка",
            "Исследования технологий": "Наука",
            "Обучить Солдат": "Тренировка"
        }
    },
    en: {
        theme_dark: "🌙 Dark",
        theme_light: "☀️ Light",
        lang_name: "🇺🇸 EN",
        loading: "Loading...",
        next_event: "➡ {event} in {h}h {m}m",
        no_next_event: "➡ No upcoming events",
        current_active_event: "🔥 NOW ACTIVE: {event}",
        current_active_phase_event: "🔥 Phase {phase}: {event}",
        day_label: "Day",
        local_time: "🕒 Local Time",
        server_time: "🖥️ Server Time (UTC-2)",
        game_day: "📅 Game Day",
        timezone: "Timezone",
        phase_radar: "Phase 1. Radar",
        phase_build: "Phase 2. Construction",
        phase_tech: "Phase 3. Technology",
        phase_hero: "Phase 4. Hero",
        phase_prepare: "Phase 5. Readiness",
        phase_raid: "Phase 6. Raid",
        days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
        events: {
            "Строительство Базы": "Base Construction",
            "Обучить Солдат": "Train Soldiers",
            "Исследования технологий": "Tech Research",
            "Улучшение бойца": "Fighter Upgrade",
            "Улучшение Героя": "Hero Upgrade"
        },
        tabs: {
            phases: "📅 Phases",
            score: "🏆 Phase Points",
            upgrades: "🏗️ Upgrades",
            calendar: "🗓️ Events",
            timecalc: "⏱️ Sum Calculator",
            resources: "💰 Resources",
            itemupgrade: "⚡ Golden Items",
            guides: "📖 Guides",
            codes: "🎁 Codes",
            video: "🎥 Video",
            support: "🙏 Support"
        },
        ui: {
            total: "Total",
            points: "points",
            next_chest: "Next chest",
            all_chests: "All chests obtained!",
            add_points: "➕ Add points",
            select_level: "Select base level (1–30):",
            level: "Level",
            condition: "Condition",
            no_data: "No data",
            calc_time: "🧮 Time Calculator",
            reset: "Reset",
            reset_all: "Reset All",
            add: "Add",
            subtract: "Subtract",
            qty: "Qty",
            duration: "Dur.",
            items: "Items (click to select):",
            conv_title: "🔁 Component Conversion",
            calculate: "Calculate",
            gear_title: "⚡ Golden Gear Leveling (0–40)",
            gear_desc: "Enter current and target levels. Cost in refined stones and oil.",
            current_lvl: "Current level",
            target_lvl: "Target level",
            stars_title: "⭐ Star Leveling (1⭐ and 2⭐)",
            stars_desc: "To get a star, you need to perform 5 upgrades at a fixed price.",
            star1: "1 star (5×12,000 stones, 5×145 crystals, 5×20m oil)",
            star2: "2 star (5×16,000 stones, 5×200 crystals, 5×30m oil)",
            calc_star: "Calculate star cost",
            stones: "Refined stones",
            oil: "Oil",
            crystals: "Conductive crystals",
            reminders: "Reminder for",
            current_phase: "🔹 Current phase",
            next_phase_rem: "⏰ To next phase",
            no_next_phase: "⏰ To next phase: no data",
            item_qty_err: "Quantity > 0",
            select_item_err: "Select an item",
            gear_lvl_err: "Target level must be higher than current level",
            no_gear_data: "No data for level",
            st_d: "d",
            st_h: "h",
            st_m: "m",
            st_s: "s",
            pcs: "pcs",
            copy_code: "Click to copy",
            copied: "Copied!",
            vs_title: "⚙️ VS Technologies (bonuses in %)",
            vs_bonus_note: "Bonuses are cumulative. Points are recalculated automatically.",
            items_header: "📦 Items (click to select):",
            conv_chain_desc: "Chain: 4 Steel ▸ 1 Steel Component ▸ 4 ▸ Heat-resistant Gold ▸ 4 ▸ Composite Material ▸ 4 ▸ Conductive Crystal (1 crystal = 256 steel).",
            star1_label: "1 star (5×12,000 stones, 5×145 crystals, 5×20m oil)",
            star2_label: "2 star (5×16,000 stones, 5×200 crystals, 5×30m oil)",
            vs_hint: "🎯 VS Points",
            bonus_labels: {
                "vs_radar": "📡 Radar",
                "vs_build": "🏗️ Construction",
                "vs_research": "🔬 Research",
                "vs_train": "⚔️ Training",
                "vs_hire": "🦸 Hero Hire",
                "vs_speed": "⚡ Speedup",
                "vs_kill": "💀 Kill/Loss",
                "vs_all": "✨ Overall (all actions)"
            },
            resources: {
                steel: "Steel",
                steelComp: "Steel Component",
                heatGold: "Heat-resistant Gold",
                composite: "Composite Material",
                crystal: "Conductive Crystal"
            },
            res_names: {
                steel: "steel",
                steelComp: "steel components",
                heatGold: "heat-resistant gold",
                composite: "composite material",
                crystal: "conductive crystals"
            },
            main_subtitle: '<span class="paw">🐾</span> HIS FLUFFINESS <span class="paw">🐾</span>',
            select_lvl_req: "Select a level to see requirements",
            th_action: "Action",
            th_base: "Base Points",
            th_qty: "Quantity / Total",
            th_total: "Total",
            k_exp: "k EXP",
            total_units: "total units",
            support_html: `
                <h3>🙏 Thanks for using the assistant!</h3>
                <p>If this tool helps you in the game and you want to support its development, you can make a voluntary donation. All funds will go towards server maintenance and creating new guides.</p>
                <p><strong>Important:</strong> Donation is voluntary and does not provide any advantages in the game or in using the assistant. You can use all features completely for free.</p>
                <p>Support Details:</p>
                <ul style="text-align: left; display: inline-block;">
                    <li>MTS (RU): 2203 8302 4197 6290 </li>
                    <li><a href="https://boosty.to/peg40/donate" target="_blank">Support project on Boosty</a></li>
                </ul>
                <p style="margin-top: 12px;">Or message in-game (TG/Email later) <strong>RESERVE</strong> for other methods.</p>
                <p class="small-note" style="margin-top: 12px;">This site is not a public offer. All payments are voluntary.</p>
            `,
            calendar_day: "Day {n}"
        },
        buildings: {
            "Полигон": "Training Ground",
            "Парковка": "Parking",
            "Линия обороны": "Defense Line",
            "Тренировочный лагерь солдат": "Soldier Training Camp",
            "Центр подготовки (по классу)": "Preparation Center (by class)",
            "Отдел альфа-исследований": "Alpha Research Dept",
            "Центр альянса": "Alliance Center",
            "Госпиталь": "Hospital",
            "Ур.": "Lvl."
        },
        tips: {
            "Sunday": ["📡 Don't complete radar tasks — save them until Monday.", "🚚 Send squads to gather resources overnight.", "⚡ Prepare stamina and bottles."],
            "Monday": ["🎯 Complete saved radar tasks immediately.", "💪 Use fighter parts, combat chips, and stamina.", "🔄 Constantly send squads to gather resources.", "🤝 Combine with Mission Readiness."],
            "Tuesday": ["🏗️ Complete 'ghost construction'.", "📈 Use construction speedups.", "✉️ Complete an orange mission and send a legendary transport."],
            "Wednesday": ["🔬 Don't use research speedups all week — use them today.", "📡 Close radar.", "📦 Open component chests.", "🧪 Request Minister of Science."],
            "Thursday": ["🦸 Use hero EXP and recruit cards.", "🎴 Spend hero fragments (mythic→epic→rare).", "📖 Apply skill books.", "📡 Save radar for tomorrow."],
            "Friday": ["⚔️ Combine construction, research, and training speedups.", "🎓 Train soldiers in intervals.", "🛡️ Prepare a shield for Saturday."],
            "Saturday": ["🏆 Use remaining speedups.", "⚔️ Participate in raids, kill soldiers.", "🛡️ Don't fear losses — they give points.", "🚫 Disable garrison defense, keep resources in inventory."]
        },
        guides: [
            { 
                title: "💎 How to save diamonds?", 
                body: "1. Daily tasks (up to 500 per day).\n2. Radar tasks (especially orange ones).\n3. Alliance events (chest rewards).\n4. Special ops and elite zombies.\n5. Alliance gifts from clan purchases.\n\nTip: Don't spend diamonds on speedups directly; better buy VIP points or discounted items in the shop." 
            },
            { 
                title: "⚔️ How to prepare for the Raid (Saturday)?", 
                body: "1. Save shields (8h or 24h).\n2. Recruit more troops on Friday.\n3. Hide resources in your inventory (don't open chests).\n4. Remove troops from defense if you don't plan to defend.\n\nRemember: On Saturday, the main thing is to kill enemy troops, not to protect the base." 
            },
            { 
                title: "🏗️ Construction Priorities", 
                body: "1. Base (unlocks new levels).\n2. Training camps (increase troop level).\n3. Science Center (speeds up development).\n4. Training Ground (increases squad size).\n\nTip: Build only what is necessary to upgrade the Base to reach T9/T10 troops faster." 
            }
        ],
        videos: [
            {
                title: "Server Jump",
                description: "Video guide: how to jump from one server to another.",
                src: "assets/video/ServJ.mp4"
            }
        ],
        phase_names: ["Radar", "Construction", "Technology", "Hero", "Readiness", "Raid"],
        calendar_days: ["Day 1 (Sunday)","Day 2 (Monday)","Day 3 (Tuesday)","Day 4 (Wednesday)","Day 5 (Thursday)","Day 6 (Friday)","Day 7 (Saturday)"],
        phase_tips: {
            "Воскресенье": "📡 Save Radar",
            "Понедельник": "🎯 Radar + Gathering",
            "Вторник": "🏗️ Build",
            "Среда": "🔬 Tech",
            "Четверг": "🦸 Heroes",
            "Пятница": "⚔️ Readiness",
            "Суббота": "🏆 Raid"
        },
        score_actions: {
            "Потратить 1 Выносливость": "Spend 1 Stamina",
            "Выполнить задание Радара": "Complete Radar Task",
            "Использовать 660 опыта Героя": "Use 660 Hero EXP",
            "Набор с алмазами [1 алмаз]": "Diamond Pack [1 diamond]",
            "Собрать 100 ед. еды": "Gather 100 Food",
            "Собрать 100 ед. металла": "Gather 100 Metal",
            "Собрать 60 ед. нефти": "Gather 60 Oil",
            "Использовать 1 Боевой чип бойца": "Use 1 Combat Chip",
            "Использовать 1 Часть бойца": "Use 1 Fighter Part",
            "За каждую минуту ускорения постройки": "Per minute of building speedup",
            "За каждую постройку +1 Мощь": "Per building +1 Power",
            "Выполнить 1 оранжевую миссию Спецопераций": "Complete 1 orange Special Ops mission",
            "Отправить 1 Легендарный Транспортник": "Send 1 Legendary Transport",
            "Провести 1 призыв выжившего": "Perform 1 survivor recruit",
            "Завершить событие Радара": "Complete Radar Event",
            "Использовать 1 минуту ускорения исследования": "Use 1 minute of research speedup",
            "Завершить исследование за +1 Силу": "Complete research for +1 Power",
            "Потратить 1 Научные данные": "Spend 1 Scientific Data",
            "Открыть сундук с компонентами бойца": "Open fighter component chest",
            "Нанять героя 1 раз": "Hire hero 1 time",
            "Использовать 1 Мифический Осколок Героя": "Use 1 Mythic Hero Shard",
            "Использовать 1 Эпический Осколок Героя": "Use 1 Epic Hero Shard",
            "Использовать 1 Редкий Осколок Героя": "Use 1 Rare Hero Shard",
            "Использовать 1 Книгу опыта навыков": "Use 1 Skill EXP Book",
            "За каждую минуту ускорения исследований": "Per minute of research speedup",
            "За каждое исследование +1 Сила": "Per research +1 Power",
            "Ускорение тренировок (1 мин.)": "Training speedup (1 min)",
            "Обучить Т1 Солдата": "Train T1 Soldier",
            "Обучить Т2 Солдата": "Train T2 Soldier",
            "Обучить Солдата Т3": "Train T3 Soldier",
            "Обучить Солдата Т4": "Train T4 Soldier",
            "Обучить Солдата Т5": "Train T5 Soldier",
            "Обучить Солдата Т6": "Train T6 Soldier",
            "Обучить Солдата Т7": "Train T7 Soldier",
            "Обучить Солдата Т8": "Train T8 Soldier",
            "Облучить Солдата Т8": "Train T8 Soldier",
            "За каждого уничтоженного бойца T7": "Per T7 soldier destroyed",
            "За каждого уничтоженного солдата T8": "Per T8 soldier destroyed",
            "За каждого уничтоженного солдата T9": "Per T9 soldier destroyed",
            "За каждого уничтоженного солдата T10": "Per T10 soldier destroyed",
            "За каждого потерянного солдата T1": "Per T1 soldier lost",
            "За каждого потерянного солдата T2": "Per T2 soldier lost",
            "За каждого потерянного солдата T3": "Per T3 soldier lost",
            "За каждого погибшего солдата T4": "Per T4 soldier died",
            "За каждого погибшего солдата T5": "Per T5 soldier died",
            "За каждого погибшего солдата T6": "Per T6 soldier died",
            "За каждого погибшего солдата T7": "Per T7 soldier died",
            "За каждого погибшего солдата T8": "Per T8 soldier died",
            "За каждого погибшего солдата T9": "Per T9 soldier died",
            "За каждого потерянного бойца T10": "Per T10 soldier lost"
        },
        phases_raw: [
            ["Sunday", "", "Radar Events (Save for tomorrow)", "Send squads to gather resources overnight."],
            ["Monday", "Phase 1. Radar", "Complete Radar Event", "Complete saved radar tasks immediately."],
            ["", "", "Use 1 Fighter Part", "Use fighter parts."],
            ["", "", "Use 1 Combat Chip", "Use combat chips."],
            ["", "", "Spend 1 Stamina", "Spend stamina on radar tasks."],
            ["", "", "Use 660 Hero EXP", "Save for hero phase."],
            ["", "", "Gather 100 resources", "As soon as squads return, send them back to gather."],
            ["Tuesday", "Phase 2. Construction", "Use 1 min construction speedup", "Complete pre-started buildings."],
            ["", "", "Complete building for +1 Power", "Use construction speedups."],
            ["", "", "Complete 1 orange mission", "Use search tokens."],
            ["", "", "Send 1 Legendary Transport", "Use convoy contracts."],
            ["", "", "", "Radar Events (Save for tomorrow)."],
            ["Wednesday", "Phase 3. Technology", "Complete Radar Event", "Complete all available radar events."],
            ["", "", "Use 1 min research speedup", "Use research speedups."],
            ["", "", "Complete research for +1 Power", "Complete the longest technologies."],
            ["", "", "Spend 1 Scientific Data", "Spend scientific data."],
            ["", "", "Open fighter component chest", "Open all saved chests."],
            ["Thursday", "Phase 4. Hero", "Use 660 Hero EXP", "Use hero EXP."],
            ["", "", "Use hero recruit card", "Use recruit cards first."],
            ["", "", "Hero fragment (Mythic)", "Spend mythic fragments."],
            ["", "", "Hero fragment (Epic)", "Spend epic fragments."],
            ["", "", "Hero fragment (Rare)", "Spend rare fragments."],
            ["", "", "Use skill book", "Apply skill books."],
            ["", "", "", "Radar Events (Save for tomorrow)."],
            ["Friday", "Phase 5. Readiness", "Complete Radar Event", "Close radar."],
            ["", "", "Use 1 min construction speedup", "Use construction speedups."],
            ["", "", "Complete building for +1 Power", "Complete buildings."],
            ["", "", "Use 1 min research speedup", "Use research speedups."],
            ["", "", "Complete research for +1 Power", "Complete research."],
            ["", "", "Use 1 min training speedup", "Use training speedups."],
            ["", "", "Train soldiers", "Start training soldiers (points immediately)."],
            ["Saturday", "Phase 6. Raid", "Use 1 min construction speedup", "Use remaining construction speedups."],
            ["", "", "Use 1 min research speedup", "Use remaining research speedups."],
            ["", "", "Use 1 min training speedup", "Use remaining training speedups."],
            ["", "", "Use 1 min healing speedup", "Use healing speedups."],
            ["", "", "Kill enemy soldiers", "Attack bases, kill soldiers."],
            ["", "", "Death of your soldiers", "Don't fear losses — they give points."]
        ],
        base_score: {
            "Radar":[["Spend 1 Stamina",150],["Complete Radar Task",10000],["Use 660 Hero EXP",1],["Diamond Pack [1 diamond]",30],["Gather 100 Food",20],["Gather 100 Metal",20],["Gather 60 Oil",20],["Use 1 Combat Chip",3],["Use 1 Fighter Part",2500]],
            "Construction":[["Diamond Pack [1 diamond]",30],["Per minute of building speedup",60],["Per building +1 Power",10],["Complete 1 orange Special Ops mission",75000],["Send 1 Legendary Transport",100000],["Perform 1 survivor recruit",1500]],
            "Technology":[["Complete Radar Event",10000],["Use 1 minute of research speedup",60],["Per research +1 Power",10],["Spend 1 Scientific Data",100],["Open fighter component chest",500]],
            "Hero":[["Use 660 Hero EXP",1],["Diamond Pack [1 diamond]",30],["Hire hero 1 time",1500],["Use 1 Mythic Hero Shard",10000],["Use 1 Epic Hero Shard",3500],["Use 1 Rare Hero Shard",1000],["Use 1 Skill EXP Book",10]],
            "Readiness":[["Complete Radar Task",10000],["Diamond Pack [1 diamond]",30],["Per minute of building speedup",60],["Per building +1 Power",10],["Per minute of research speedup",60],["Per research +1 Power",10],["Training speedup (1 min)",60],["Train T1 Soldier",20],["Train T2 Soldier",30],["Train T3 Soldier",40],["Train T4 Soldier",50],["Train T5 Soldier",60],["Train T6 Soldier",70],["Train T7 Soldier",80],["Train T8 Soldier",90]],
            "Raid":[["Per T7 soldier destroyed",18],["Per T8 soldier destroyed",20],["Per T9 soldier destroyed",23],["Per T10 soldier destroyed",25],["Per T1 soldier lost",4],["Per T2 soldier lost",6],["Per T3 soldier lost",8],["Per T4 soldier died",10],["Per T5 soldier died",12],["Per T6 soldier died",14],["Per T7 soldier died",16],["Per T8 soldier died",18],["Per T9 soldier died",20],["Per T10 soldier lost",22],["Send 1 Legendary Transport",200000]]
        },
        event_labels: {
            "Улучшение бойца": "Fighter",
            "Улучшение Героя": "Hero",
            "Строительство Базы": "Build",
            "Исследования технологий": "Research",
            "Обучить Солдат": "Train"
        }
    }
};
